Refactor for Records
Records is an API on top of SQLAlchemy.
https://github.com/kennethreitz/records

At first, I didn't think I would need psycopg2 with Records. However,
attempts to uninstall resulted in SQLAlchemy traceback errors:
File "<PATH/pipenv-hash>/lib/python3.7/site-packages/sqlalchemy/\
dialects/postgresql/psycopg2.py", line 632, in dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'

As explained in https://docs.sqlalchemy.org/en/latest/intro.html:
> SQLAlchemy is designed to operate with a DBAPI implementation built
> for a particular database, and includes support for the most popular
> databases. The individual database sections in Dialects enumerate the
> available DBAPIs for each database, including external links.

SQLAlchemy therefore requires additional tooling to connect to the
PostgreSQL database. I was previously using psycopg2, which has been
split into two packages, psycopg2 and psycopg2-binary:
http://initd.org/psycopg/articles/2018/02/08/psycopg-274-released/

The postgres package is another option written on top of psycopg2.
https://postgres-py.readthedocs.io/en/latest/

Other changes include support for the DATABASE_URL environment variable
and use of SQL files for queries instead of triple-quoted strings.